### ISSUE TITLE
$redmine removeの不具合修正

### ISSUE THREAD

**Issue by wanshot** [beproud/beproudbot#152]
### 現象

- `$redmine remove #hoge` を打つとエラーが発生する

```
Traceback (most recent call last):
  File "/home/haro/venv/lib/python3.5/site-packages/redminelib/engines/base.py", line 150, in process_response
    return response.json()
  File "/home/haro/venv/lib/python3.5/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/haro/venv/lib/python3.5/site-packages/slackbot/dispatcher.py", line 55, in _dispatch_msg_handler
    func(Message(self._client, msg), *args)
  File "/home/haro/beproudbot/src/haro/plugins/redmine.py", line 209, in unregister_room
    project, project_channel = project_channel_from_identifier(user.api_key, project_identifier, s)
  File "/home/haro/beproudbot/src/haro/plugins/redmine.py", line 53, in project_channel_from_identifier
    project = redmine.project.get(identifier.strip())
  File "/home/haro/venv/lib/python3.5/site-packages/redminelib/managers.py", line 115, in get
    return self.to_resource(self.request(False, **self.params))
  File "/home/haro/venv/lib/python3.5/site-packages/redminelib/managers.py", line 54, in request
    return self.redmine.engine.request('get', self.url, params=params)[self.container]
  File "/home/haro/venv/lib/python3.5/site-packages/redminelib/engines/base.py", line 75, in request
    return self.process_response(self.session.request(method, url, **kwargs), return_raw)
  File "/home/haro/venv/lib/python3.5/site-packages/redminelib/engines/base.py", line 152, in process_response
    raise exceptions.JSONDecodeError(response)
redminelib.exceptions.JSONDecodeError: Unable to decode received JSON, you can inspect exception's "response" attribute to find out what the response was
```

### 入出力

- `$redmine remove #hoge` 

### 関連機能、影響範囲

- redmineコマンド

### セキュリティ

- なし
### デモ方法

- `$redmine remove #hoge`

**Comment by pjxiao** [comment]
# 修正案

- プロジェクトの ID として任意文字列を受け取らず、 `^[a-Z0-9-_]+$` あたりに制限する

**Comment by pjxiao** [comment]
まちがい

**Comment by pjxiao** [comment]
リリース済みクローズ
