### ISSUE TITLE
MySQL server has gone awayが多発する問題

### ISSUE THREAD

**Issue by wanshot** [beproud/beproudbot#206]
### 内容

```
Oct 07 11:13:31 haro python[5174]: Traceback (most recent call last):
Oct 07 11:13:31 haro python[5174]:   File "/home/haro/venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 703, in _finalize_fairy
Oct 07 11:13:31 haro python[5174]:     fairy._reset(pool)
Oct 07 11:13:31 haro python[5174]:   File "/home/haro/venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 873, in _reset
Oct 07 11:13:31 haro python[5174]:     pool._dialect.do_rollback(self)
Oct 07 11:13:31 haro python[5174]:   File "/home/haro/venv/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 1775, in do_r
Oct 07 11:13:31 haro python[5174]:     dbapi_connection.rollback()
Oct 07 11:13:31 haro python[5174]:   File "/home/haro/venv/lib/python3.6/site-packages/pymysql/connections.py", line 792, in rollback
Oct 07 11:13:31 haro python[5174]:     self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
Oct 07 11:13:31 haro python[5174]:   File "/home/haro/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1092, in _execute_comman
Oct 07 11:13:31 haro python[5174]:     self._write_bytes(packet)
Oct 07 11:13:31 haro python[5174]:   File "/home/haro/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1044, in _write_bytes
Oct 07 11:13:31 haro python[5174]:     "MySQL server has gone away (%r)" % (e,))
Oct 07 11:13:31 haro python[5174]: pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
Oct 07 11:13:32 haro python[5174]: reconnected to slack rtm websocket
Oct 07 11:13:31 haro python[5174]:     dbapi_connection.rollback()
Oct 07 11:13:31 haro python[5174]:   File "/home/haro/venv/lib/python3.6/site-packages/pymysql/connections.py", line 792, in rollback
Oct 07 11:13:31 haro python[5174]:     self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
Oct 07 11:13:31 haro python[5174]:   File "/home/haro/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1092, in _execute_comman
Oct 07 11:13:31 haro python[5174]:     self._write_bytes(packet)
Oct 07 11:13:31 haro python[5174]:   File "/home/haro/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1044, in _write_bytes
Oct 07 11:13:31 haro python[5174]:     "MySQL server has gone away (%r)" % (e,))
Oct 07 11:13:31 haro python[5174]: pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
Oct 07 11:13:32 haro python[5174]: reconnected to slack rtm websocket
Oct 07 11:16:35 haro CRON[12048]: pam_unix(cron:session): session closed for user root
Oct 07 11:17:01 haro CRON[12128]: pam_unix(cron:session): session opened for user root by (uid=0)
Oct 07 11:17:01 haro CRON[12129]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 07 11:17:01 haro CRON[12128]: pam_unix(cron:session): session closed for user root
Oct 07 11:46:35 haro python[5174]: lost websocket connection, try to reconnect now
Oct 07 11:46:38 haro python[5174]: reconnected to slack rtm websocket
```

**Comment by wanshot** [comment]
Ubuntu 18.04.5にアップデートした時に以下の設定が抜けて発生しているっぽい

https://github.com/beproud/beproudbot/pull/102/files

**Comment by wanshot** [comment]
systemdではenvファイル指定しているのでそんな事なかった。 `SQLALCHEMY_POOL_SIZE=40 -> 60` にして一旦様子見

**Comment by wanshot** [comment]
再発してないのでclose
