### ISSUE TITLE
動作テストで見つかったバグ修正 part2

### ISSUE THREAD

**Issue by wanshot** [beproud/beproudbot#68]
### 目的

- 動作テストで見つかったバグを修正する

### 関連機能、影響範囲

- waterコマンド
- cleaningコマンド
- redmineコマンド

### セキュリティ

- 特になし

### デモ方法

waterコマンドの不具合

- SQLの条件式的にdatetimeにNoneが返ってきてしまいエラー

```
$water 1
$water count
Traceback (most recent call last):
  File "/home/haro/venv/lib/python3.5/site-packages/slackbot/dispatcher.py", line 55, in _dispatch_msg_handler
    func(Message(self._client, msg), *args)
  File "/home/haro/beproudbot/src/haro/plugins/water.py", line 33, in count_water_stock
    '%Y-%m-%d %H:%M:%S')
TypeError: strptime() argument 1 must be str, not None
```
cleaningコマンドの不具合

- 一覧に無駄な改行が入っている

```
$cleaning task
haroAPP [6:21 PM] 
- [] ゴミ集め(各机, シュレッダー) 掃除でやることリスト

- [] ゴミ出し 火曜・金曜掃除でやることリスト

- [] 机拭き: bar, showroom, 窓際, おやつ, スタンディング掃除でやることリスト

- [] フリーアドレス席の汚れている机拭き掃除でやることリスト

- [] barのディスプレイから出てるケーブルを後ろ側にある取っ手にかける掃除でやることリスト

- [] 空気清浄機のフル稼働掃除でやることリスト

- [] 加湿器の注水＆フル稼働(消し忘れ防止のためにタイマーで設定しましょう) 冬場のみ
```

- 一覧が中央寄せになっている

```
haroAPP [7:04 PM] 
+------+----------------------------------------------------------------------+
| 曜日 |                               掃除当番                               |
+------+----------------------------------------------------------------------+
|  月  |                 ray, haru, marippe, tsuyoshi, kameko                 |
|  火  |     cactusman, furi, ae35, susumuis, yyyk, fumie.tanaka, okadan      |
|  水  | hirokiky, nakagami, hydden, jamesvandyne, shimizukawa, tsutomu.saito |
|  木  |         monjudoh, kk6, altnight, crohaco, natsu, kashew_nuts         |
|  金  |                tell-k, takanory, xiao, mtb_beta, wan                 |
+------+----------------------------------------------------------------------+
```

redmineコマンドの不具合

- slackユーザー以外の投稿にも反応してしまう

```
haroAPP [7:38 PM] 
[show_ticket_information] I had a problem handling "<https://xxxxxxx> | 2017-11-14 17:20:52 +0900 | 2615848: flow: Created branch 'feature/t59162'."

Traceback (most recent call last):
  File "/home/haro/venv/lib/python3.5/site-packages/slackbot/dispatcher.py", line 55, in _dispatch_msg_handler
    func(Message(self._client, msg), *args)
  File "/home/haro/beproudbot/src/haro/plugins/redmine.py", line 52, in show_ticket_information
    user_id = message.body['user']
KeyError: 'user'
```

**Comment by wanshot** [comment]
https://github.com/beproud/beproudbot/pull/71
