### ISSUE TITLE
$randomコマンドのgroupチャンネル対応

### ISSUE THREAD

**Issue by wanshot** [beproud/beproudbot#77]
### 目的

- $randomコマンドでエラーが発生しているので修正を行う

### 入出力

- $random

```
Traceback (most recent call last):
  File "/home/haro/venv/lib/python3.5/site-packages/slackbot/dispatcher.py", line 55, in _dispatch_msg_handler
    func(Message(self._client, msg), *args)
  File "/home/haro/beproudbot/src/haro/plugins/random.py", line 33, in random_command
    cinfo = webapi.channels.info(channel)
  File "/home/haro/venv/lib/python3.5/site-packages/slacker/__init__.py", line 256, in info
    return self.get('channels.info', params={'channel': channel})
  File "/home/haro/venv/lib/python3.5/site-packages/slacker/__init__.py", line 90, in get
    api, **kwargs
  File "/home/haro/venv/lib/python3.5/site-packages/slacker/__init__.py", line 72, in _request
    raise Error(response.error)
slacker.Error: channel_not_found
```

### 関連機能、影響範囲

- $randomコマンド

### セキュリティ

- 特になし

### デモ方法

- $random

**Comment by wanshot** [comment]
https://github.com/beproud/beproudbot/pull/78
