### ISSUE TITLE
Python3.7 or 3.8 対応

### ISSUE THREAD

**Issue by wanshot** [beproud/beproudbot#87]
### 目的

- Python3.7 or 3.8 に対応する

### 入出力

- 後で書く

### 関連機能、影響範囲

- 全体

### セキュリティ

- 後で書く

### デモ方法

- 後で書く

**Comment by wanshot** [comment]
#56

**Comment by fumi232323** [comment]
* Python3.7 or Python3.8 にできると良さそう
* Python3.7.5 で app が正常動作するのは確認済み (fumi23 ローカル)
* Ubuntu18.04 からは、 apt で Python3.7 も Python 3.8 も install できるとのこと

```shell
# こんな感じ
$ apt install -y python3.8
```

* Ubuntu18.04 へのアップグレード (#128 ) がうまくいったらやると良さそう
* Python3.8.5 だと、 現行バージョンのPillow (5.2.0) が pip install でエラーになる。Pillow 7.2.0 であればエラーにならない。

**Comment by fumi232323** [comment]
## 動作確認結果

* Python3.8.5: OK
  * アプリのコードはそのままでOK
  * Pillow==7.2.0 (2020.09.10 時点の最新) にする必要あり

* Python3.7.5: OK
  * アプリのコードはそのままでOK
  * Pillow==5.2.0 (2020.09.10 時点の beproudbot 現行) のままでOK

**Comment by fumi232323** [comment]
#128 で、図らずも Python3.6 化は成されたので、Title を変更

**Comment by fumi232323** [comment]
## tox 結果 memo

* 現行の `SQLAlchemy==1.2.2` だと以下のような warning が大量に出る
  *  `SQLAlchemy==1.3.19` だと出ない
  ```
  # SQLAlchemy==1.2.2 の warning 例
  /Users/fumi23/projects/beproudbot/.tox/py38/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py:403: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
    apply_kw = inspect.formatargspec(name_args, spec[1], spec[2],
  ```

**Comment by fumi232323** [comment]
## 動作確認でエラーの出るコマンドメモ

エラーの出るコマンドは以下の 1つ

* `$<command> pop`: 最後に自分が登録した語録を削除する

### エラー内容

```python
Traceback (most recent call last):
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 798, in visit_textual_label_reference
   col = with_cols[element.element]
KeyError: '-id'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/slackbot/dispatcher.py", line 55, in _dispatch_msg_handler
   func(Message(self._client, msg), *args)
 File "/Users/fumi23/projects/beproudbot/src/haro/arg_validator.py", line 125, in wrapper
   return func(**validator.cleaned_data)
 File "/Users/fumi23/projects/beproudbot/src/haro/plugins/create.py", line 216, in run_command
   pop_term(message, command)
 File "/Users/fumi23/projects/beproudbot/src/haro/plugins/create.py", line 244, in pop_term
   term = (s.query(Term)
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3402, in first
   ret = list(self[0:1])
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3176, in __getitem__
   return list(res)
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
   return self._execute_and_instances(context)
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
   result = conn.execute(querycontext.statement, self._params)
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
   return meth(self, multiparams, params)
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
   return connection._execute_clauseelement(self, multiparams, params)
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1115, in _execute_clauseelement
   compiled_sql = elem.compile(
 File "<string>", line 1, in <lambda>
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 481, in compile
   return self._compiler(dialect, bind=bind, **kw)
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 487, in _compiler
   return dialect.statement_compiler(dialect, self, **kw)
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 593, in __init__
   Compiled.__init__(self, dialect, statement, **kwargs)
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 322, in __init__
   self.string = self.process(self.statement, **compile_kwargs)
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 353, in process
   return obj._compiler_dispatch(self, **kwargs)
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
   return meth(self, **kw)
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 2164, in visit_select
   text = self._compose_select_body(
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 2277, in _compose_select_body
   text += self.order_by_clause(select, **kwargs)
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 2336, in order_by_clause
   order_by = select._order_by_clause._compiler_dispatch(self, **kw)
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
13:58
return meth(self, **kw)
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 1003, in visit_clauselist
   text = sep.join(
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 1003, in <genexpr>
   text = sep.join(
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 1006, in <genexpr>
   c._compiler_dispatch(self, **kw) for c in clauselist.clauses
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
   return meth(self, **kw)
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 800, in visit_textual_label_reference
   elements._no_text_coercion(
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 4748, in _no_text_coercion
   util.raise_(
 File "/Users/fumi23/projects/beproudbot/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
   raise exception
sqlalchemy.exc.CompileError: Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression '-id' should be explicitly declared as text('-id')
```

### 原因

SQLA をバージョンアップしたので、その影響と思われる (詳しくは見ていないので追ってよく見る)

* `SQLAlchemy==1.2.2` => `SQLAlchemy==1.3.19`
