### ISSUE TITLE
「MySQL server has gone away」が発生する

### ISSUE THREAD

**Issue by wanshot** [beproud/beproudbot#96]
```
Traceback (most recent call last):
  File "/home/haro/venv/lib/python3.5/site-packages/pymysql/connections.py", line 1039, in _write_bytes
    self._sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/haro/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/haro/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/home/haro/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/haro/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/haro/venv/lib/python3.5/site-packages/pymysql/connections.py", line 855, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/haro/venv/lib/python3.5/site-packages/pymysql/connections.py", line 1092, in _execute_command
    self._write_bytes(packet)
  File "/home/haro/venv/lib/python3.5/site-packages/pymysql/connections.py", line 1044, in _write_bytes
    "MySQL server has gone away (%r)" % (e,))
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/haro/venv/lib/python3.5/site-packages/slackbot/dispatcher.py", line 55, in _dispatch_msg_handler
    func(Message(self._client, msg), *args)
  File "/home/haro/beproudbot/src/haro/plugins/thx.py", line 48, in update_thx
    user_dict = check_user_name(s, user_names)
  File "/home/haro/beproudbot/src/haro/plugins/thx.py", line 94, in check_user_name
    slack_id = get_slack_id(session, name)
  File "/home/haro/beproudbot/src/haro/alias.py", line 19, in get_slack_id
    .filter(UserAliasName.alias_name == user_name)
  File "/home/haro/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2843, in scalar
    ret = self.one()
  File "/home/haro/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2814, in one
    ret = self.one_or_none()
  File "/home/haro/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
    ret = list(self)
  File "/home/haro/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/home/haro/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/haro/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/haro/venv/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/haro/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/haro/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/haro/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/haro/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/haro/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/haro/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/haro/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/home/haro/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/haro/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/haro/venv/lib/python3.5/site-packages/pymysql/connections.py", line 855, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/haro/venv/lib/python3.5/site-packages/pymysql/connections.py", line 1092, in _execute_command
    self._write_bytes(packet)
  File "/home/haro/venv/lib/python3.5/site-packages/pymysql/connections.py", line 1044, in _write_bytes
    "MySQL server has gone away (%r)" % (e,))
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))") [SQL: 'SELECT user_alias_name.slack_id AS user_alias_name_slack_id \nFROM user_alias_name \nWHERE user_alias_name.alias_name = %(alias_name_1)s'] [parameters: {'alias_name_1': 'tsutomu'}]
```

**Comment by Checkroth** [comment]
http://docs.sqlalchemy.org/en/latest/core/pooling.html#disconnect-handling-pessimistic

DBへの接続が死んだりしているみたいなので、Session開く時にPingすれば良さそう。

- Pingして
- 大丈夫であれば普通に進む
- コネクションが悪ければ、ConnectionPoolから消して接続しなおす

リクエスト毎クエリが一つ増えることになるけど、重くないと思います。のちほどPR作ります

**Comment by shimizukawa** [comment]
その前に、 pool_recycleを設定してみてください。

http://docs.sqlalchemy.org/en/latest/core/pooling.html#setting-pool-recycle

設定はここに書くのだと思う
https://github.com/beproud/beproudbot/blob/172407197ee1115df064955a9907fa65586a2a6b/src/alembic/conf.ini#L3-L7

値は、MySQL側のwait_timeout値(default=28800)に合わせて下さい。
https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_wait_timeout

**Comment by Checkroth** [comment]
`pool_pre_ping` はもう設定してあるじゃん

**Comment by Checkroth** [comment]
一応 `pool_recycle` 入れたけど、もうちょっと考えた方が良さそう。。。

- `pool_pre_ping` は設定してあるので、`pool_recycle` 入れてもバグ解決しないかもしれない
- `28800` に設定するより、環境変数から読んだ方が良さそう（28800は環境変数ない時のみ）

  - MySqlの wait_timeout設定はしていなさそうなのでこの大丈夫かな

**Comment by wanshot** [comment]
* 原因 

`alembic.conf.ini` に記載した以下の設定値が反映されていなかった。

* 解決案

`engine_from_config` でprefixに 'sqlalchemy.' を設定している為以下のようにする必要がある

```
sqlalchemy.pool_size = 20
sqlalchemy.pool_pre_ping = True
```

また、 `pool_pre_ping` はSQLAlchemy=1.2からのオプションの為、`SQLAlchemy==1.1.14` からバージョンアップが必要(但しbeta版)

また、pool_sizeはSQLiteだとエラーが発生する為環境変数から渡した方がよいと思う

**Comment by wanshot** [comment]
https://github.com/beproud/beproudbot/pull/102
